# Qdrant Production Configuration
# Location: deployment/qdrant-config.yaml

log_level: INFO

storage:
  # Storage configuration for production
  storage_path: ./storage
  snapshots_path: ./snapshots
  
  # Performance optimization
  performance:
    max_search_threads: 0  # Auto-detect based on CPU cores
    max_optimization_threads: 1
    indexing_threshold: 20000
    
  # Memory management
  memory:
    max_indexing_memory_kb: 2097152  # 2GB
    
  # Write-ahead log configuration
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0

service:
  # Network configuration
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  
  # Enable CORS for web access
  enable_cors: true
  
  # Max request size (50MB for large embeddings)
  max_request_size_mb: 50
  
  # Connection limits
  max_concurrent_connections: 100

cluster:
  # Disable clustering for single-node setup
  enabled: false

telemetry:
  # Disable telemetry for privacy
  disabled: true